[2024/04/20] - c++: 1문제 / [mungjin01]
ALGOHAZA-Study/Algorithm-Study pull request #10
Opened 2024-04-20 13:57 UTC by Mungjin01

## 📋 풀이한 문제 목록

- `[ 20240420 : 2579 : 계단 오르기 ]` - `https://www.acmicpc.net/problem/2579`

## 💡 각 문제에 대한 간단한 소개
`2579 번 : 계단 오르` : 
    계단을 오르면서 얻을 수 있는 점수의 최댓값을 구하는 문제

## ❗ 문제 풀이로 깨달은 점

💡 작성 예시 : dp 접근법에 복습하는 시간을 가짐..?

---

## 🚨 `PR` 제출 전 `Check List` 검토

- [x] 각 문제당 아래의 파일들을 포함하였나요?
    - [x]   `문제의 간략한 설명`    파일
    - [x]   `문제의 풀이 방법 정리` 파일
    - [x]   `문제 해결 인증 스크린샷`
    - [ ]   `정답 소스코드`         파일

- [ ]   최소 1 문제 이상 풀이하셨나요?
- [ ]   풀이한 문제들 알고리즘 유형에 따른 `tag` 를 지정하셨나요? `(DP, Heap 등)`
- [ ]   알고리즘 제공 사이트에 따른 `tag` 를 지정하셨나요? `(BAJ, PRG 등)`

**<ins>위 체크리스트를 모두 만족하지 못할 시, `PR` 이 회고될 수 있습니다!</ins>**

만약 포함되지 않은 파일이 있다면 누락된 파일을 포함시켜 주세요. 알고리즘 사이트에 따른 `tag` 는 다음과 같습니다.

|`플랫폼`|`태그`|
|:---:|:---:|
|`백준`|`BAJ`|
|`프로그래머스`|`PRG`|
|`LeetCode`|`LTC`|
|`기타`|`ETC`|

아래의 체크리스트는 **원활한 `PR` 리뷰를 위해 권장되는 사항들** 입니다.

- [ ]   각 파일을 `markdown` 으로 제작하셨나요?
- [ ]   `PR` 템플릿을 준수해 작성하셨나요?
- [ ]   `Assignees` 에 관리자를 지정하셨나요? `(jbw9964 등)`

`Assignees` 에 관리자를 지정해야 관리자 이메일로 알림이 옵니다. 정기적으로 확인하지만 알림이 온다면 더 빨리 확인할 수 있습니다!

---

2024-04-20 14:55 UTC, jbw9964 requested changes
@Mungjin01 

`PR` 보내주신 것 중 `/.vscode` 폴더가 같이 들어왔네요.
그리고 정답 소스코드가 빈 파일로 나오니 `commit` 추가해서 `PR` 올려주세요.

2024-04-20 14:57 UTC, jbw9964 commented
> @Mungjin01
> 
> `PR` 보내주신 것 중 `/.vscode` 폴더가 같이 들어왔네요. 그리고 정답 소스코드가 빈 파일로 나오니 `commit` 추가해서 `PR` 올려주세요.

다시 `PR` 보내는 건 오늘까지 마감이 아니니 천천히 보내주셔도 됩니다.
다음주 수요일 전까지만 수정 하시면 됩니다.
(수요일 `PR` 과 별도)

2024-04-24 05:50 UTC, Mungjin01 commented
> @jbw9964 
> 
> `PR` 보내주신 것 중 `/.vscode` 폴더가 같이 들어왔네요. 그리고 정답 소스코드가 빈 파일로 나오니 `commit` 추가해서 `PR` 올려주세요.

수정했습니다!

2024-04-24 06:21 UTC, jbw9964 approved these changes
검토 완료하였습니다.

2024-04-24 06:23 UTC, merged